# Generated by Django 3.2.23 on 2023-12-04 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_medicalpersonel_hospital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_to', models.CharField(default='Mwatate Sub-County Hospital', max_length=50, verbose_name='Reported to')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Symptoms')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('disease_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo_health_app.disease')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='full name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('health_situation', models.TextField(blank=True, max_length=1000, null=True, verbose_name='health situation')),
            ],
            bases=('geo_health_app.disease',),
        ),
        migrations.CreateModel(
            name='TreatPatient',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo_health_app.patient')),
                ('ip_op_number', models.IntegerField(unique=True, verbose_name='OP Number')),
                ('height', models.FloatField(max_length=500, verbose_name='height')),
                ('bp_reading', models.FloatField(max_length=1000, verbose_name='BP Reading')),
                ('glucose_level', models.FloatField(max_length=1000, verbose_name='glucose level')),
                ('weight_reading', models.FloatField(max_length=1000, verbose_name='weight reading (kg)')),
                ('temperature_reading', models.FloatField(max_length=1000, verbose_name='temperature reading (degree celcius)')),
                ('prescribe_lab_test', models.TextField(blank=True, null=True, verbose_name='prescribe lab test')),
                ('lab_test_results', models.TextField(blank=True, null=True, verbose_name='lab test results')),
                ('drug_prescription', models.TextField(blank=True, null=True, verbose_name='drug prescription')),
                ('treatment_status', models.CharField(choices=[('Not Treated', 'Not Treated'), ('Treated', 'Treated'), ('In Progress', 'In Progress')], default='Not Treated', max_length=50, verbose_name='treatment status')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
            ],
            bases=('geo_health_app.patient',),
        ),
    ]
