# Generated by Django 4.2.6 on 2023-11-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_health_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="symptoms",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
