# Generated by Django 3.2.23 on 2023-11-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_health_app', '0002_alter_disease_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(blank=True, default=list, null=True, verbose_name='Symptoms'),
        ),
    ]
