# Generated by Django 3.2.23 on 2023-12-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_health_app', '0005_patient_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='type',
            new_name='type_l',
        ),
    ]
