# Generated by Django 4.2.7 on 2023-11-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_health_app', '0006_disease_reported_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatPatient',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo_health_app.patient')),
                ('op_number', models.IntegerField(max_length=100, verbose_name='OP Number')),
                ('height', models.FloatField(max_length=500, verbose_name='height')),
                ('bp_reading', models.FloatField(max_length=1000, verbose_name='BP Reading')),
                ('glucose_level', models.FloatField(max_length=1000, verbose_name='glucose level')),
                ('weight_reading', models.FloatField(max_length=1000, verbose_name='weight reading (kg)')),
                ('temperature_reading', models.FloatField(max_length=1000, verbose_name='temperature reading (degree celcius)')),
                ('prescribe_lab_test', models.TextField(blank=True, max_length=10000, null=True, verbose_name='prescribe lab test')),
                ('lab_test_results', models.TextField(blank=True, max_length=1000, null=True, verbose_name='lab test results')),
            ],
            bases=('geo_health_app.patient',),
        ),
    ]
