# Generated by Django 4.2.7 on 2023-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_health_app', '0007_treatpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatpatient',
            name='treatment_status',
            field=models.CharField(choices=[('Not Treated', 'Not Treated'), ('Treated', 'Treated'), ('In Progress', 'In Progress')], default='Not Treated', max_length=50, verbose_name='treatment status'),
        ),
        migrations.AlterField(
            model_name='treatpatient',
            name='lab_test_results',
            field=models.TextField(blank=True, null=True, verbose_name='lab test results'),
        ),
        migrations.AlterField(
            model_name='treatpatient',
            name='prescribe_lab_test',
            field=models.TextField(blank=True, null=True, verbose_name='prescribe lab test'),
        ),
    ]
