# Generated by Django 4.2.7 on 2023-11-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_health_app', '0008_treatpatient_treatment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatpatient',
            name='drug_prescription',
            field=models.TextField(blank=True, null=True, verbose_name='drug prescription'),
        ),
    ]
