# Generated by Django 4.2.7 on 2023-11-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_health_app', '0009_treatpatient_drug_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatpatient',
            name='kmdb_no',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatpatient',
            name='op_number',
            field=models.IntegerField(verbose_name='OP Number'),
        ),
    ]
