# Generated by Django 3.2.23 on 2023-12-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_medicalpersonel_hospital'),
        ('geo_health_app', '0010_treatpatient_kmdb_no_alter_treatpatient_op_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatpatient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital'),
        ),
    ]
