# Generated by Django 4.2.6 on 2023-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.IntegerField(null=True, verbose_name='identification'),
        ),
    ]
