# Generated by Django 3.2.23 on 2023-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_medicalpersonel_communitymember_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpersonel',
            name='kmdb_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='KMDB Number'),
        ),
    ]
